/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:834334:
  appc.background(230);
} //_CODE_:window1:834334:

public void numVolunteersSlider(GSlider source, GEvent event) { //_CODE_:numVolunteers:567666:
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:numVolunteers:567666:

public void openOrClosedBox(GCheckbox source, GEvent event) { //_CODE_:openOrClosed:345812:
  println("openOrClosed - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:openOrClosed:345812:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 400, 300, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  numVolunteers = new GSlider(window1, 104, -29, 100, 120, 10.0);
  numVolunteers.setShowValue(true);
  numVolunteers.setLimits(1, 1, 10);
  numVolunteers.setNbrTicks(10);
  numVolunteers.setShowTicks(true);
  numVolunteers.setNumberFormat(G4P.INTEGER, 0);
  numVolunteers.setOpaque(false);
  numVolunteers.addEventHandler(this, "numVolunteersSlider");
  volunteers = new GLabel(window1, -2, 18, 100, 19);
  volunteers.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  volunteers.setText("# of volunteers");
  volunteers.setOpaque(false);
  openOrClosed = new GCheckbox(window1, 16, 270, 120, 20);
  openOrClosed.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  openOrClosed.setText("Open?");
  openOrClosed.setOpaque(false);
  openOrClosed.addEventHandler(this, "openOrClosedBox");
  openOrClosed.setSelected(true);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GSlider numVolunteers; 
GLabel volunteers; 
GCheckbox openOrClosed; 
