/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void selectVolunteerMethod(GCustomSlider source, GEvent event) { //_CODE_:selectVolunteer:819496:
  println("custom_slider1 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:selectVolunteer:819496:

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:834334:
  appc.background(230);
} //_CODE_:window1:834334:

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:slider1:567666:
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider1:567666:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  selectVolunteer = new GCustomSlider(this, 100, 25, 100, 40, "grey_blue");
  selectVolunteer.setShowValue(true);
  selectVolunteer.setLimits(1, 1, 10);
  selectVolunteer.setNbrTicks(10);
  selectVolunteer.setShowTicks(true);
  selectVolunteer.setNumberFormat(G4P.INTEGER, 0);
  selectVolunteer.setOpaque(true);
  selectVolunteer.addEventHandler(this, "selectVolunteerMethod");
  Volunteers = new GLabel(this, -2, 26, 100, 20);
  Volunteers.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Volunteers.setText("# of volunteers");
  Volunteers.setOpaque(true);
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  slider1 = new GSlider(window1, 70, 40, 100, 120, 10.0);
  slider1.setLimits(0.5, 0.0, 1.0);
  slider1.setNumberFormat(G4P.DECIMAL, 2);
  slider1.setOpaque(false);
  slider1.addEventHandler(this, "slider1_change1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GCustomSlider selectVolunteer; 
GLabel Volunteers; 
GWindow window1;
GSlider slider1; 
