/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void GUIWindowDraw(PApplet appc, GWinData data) { //_CODE_:GUIWindow:359935:
  appc.background(230);
} //_CODE_:GUIWindow:359935:

public void openOrClosedBox1(GCheckbox source, GEvent event) { //_CODE_:openOrClosed1:449196:
  println("openOrClosed - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:openOrClosed1:449196:

public void weatherControl(GDropList source, GEvent event) { //_CODE_:weather:376609:
  println("weather - GDropList >> GEvent." + event + " @ " + millis());

  if (event == GEvent.CHANGED) {
    String selectedWeather = source.getSelectedText();

    // update global string used by foodDonor
    selectedWeatherName = selectedWeather;

    int type = 0; // default Sunny
    if (selectedWeather.equals("Sunny")) {
      type = 0;
    } 
    else if (selectedWeather.equals("Cloudy")) {
      type = 1;
    } 
    else if (selectedWeather.equals("Rainy")) {
      type = 2;
    } 
    else if (selectedWeather.equals("Snowy")) {
      type = 3;
    }

    // update Weather object
    weatherSystem.setWeather(type);
  }
} //_CODE_:weather:376609:

public void maxPeopleInLineSlider(GCustomSlider source, GEvent event) { //_CODE_:maxPeopleInLine:800754:
  println("maxPeopleInLine - GCustomSlider >> GEvent." + event + " @ " + millis());
  getControllerValues();
} //_CODE_:maxPeopleInLine:800754:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:515551:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:515551:

public void openOrClosedBox2(GCheckbox source, GEvent event) { //_CODE_:openOrClosed2:716764:
  println("openOrClosed2 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:openOrClosed2:716764:

public void openOrClosedBox3(GCheckbox source, GEvent event) { //_CODE_:openOrClosed3:914672:
  println("openOrClosed3 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:openOrClosed3:914672:

public void openOrClosedBox4(GCheckbox source, GEvent event) { //_CODE_:openOrClosed4:296472:
  println("openOrClosed4 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:openOrClosed4:296472:

public void startHungerControl(GDropList source, GEvent event) { //_CODE_:dropList1:810305:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList1:810305:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  GUIWindow = GWindow.getWindow(this, "GUI", 0, 0, 400, 300, JAVA2D);
  GUIWindow.noLoop();
  GUIWindow.setActionOnClose(G4P.KEEP_OPEN);
  GUIWindow.addDrawHandler(this, "GUIWindowDraw");
  openOrClosed1 = new GCheckbox(GUIWindow, 20, 200, 120, 20);
  openOrClosed1.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  openOrClosed1.setText("Window 1 Open?");
  openOrClosed1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  openOrClosed1.setOpaque(false);
  openOrClosed1.addEventHandler(this, "openOrClosedBox1");
  openOrClosed1.setSelected(true);
  weather = new GDropList(GUIWindow, 100, 60, 90, 100, 4, 10);
  weather.setItems(loadStrings("list_376609"), 0);
  weather.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  weather.addEventHandler(this, "weatherControl");
  weather2 = new GLabel(GUIWindow, 20, 60, 80, 20);
  weather2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  weather2.setText("Weather");
  weather2.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  weather2.setOpaque(false);
  maxPeopleInLine = new GCustomSlider(GUIWindow, 100, 120, 100, 40, "purple18px");
  maxPeopleInLine.setShowValue(true);
  maxPeopleInLine.setLimits(5, 5, 10);
  maxPeopleInLine.setNbrTicks(5);
  maxPeopleInLine.setShowTicks(true);
  maxPeopleInLine.setNumberFormat(G4P.INTEGER, 0);
  maxPeopleInLine.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  maxPeopleInLine.setOpaque(false);
  maxPeopleInLine.addEventHandler(this, "maxPeopleInLineSlider");
  peopleInLine = new GLabel(GUIWindow, 20, 120, 80, 40);
  peopleInLine.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  peopleInLine.setText("Max Num Of Peope In Line");
  peopleInLine.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  peopleInLine.setOpaque(false);
  button1 = new GButton(GUIWindow, 260, 130, 80, 30);
  button1.setText("Clear People");
  button1.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  openOrClosed2 = new GCheckbox(GUIWindow, 20, 250, 120, 20);
  openOrClosed2.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  openOrClosed2.setText("Window 2 Open?");
  openOrClosed2.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  openOrClosed2.setOpaque(false);
  openOrClosed2.addEventHandler(this, "openOrClosedBox2");
  openOrClosed2.setSelected(true);
  openOrClosed3 = new GCheckbox(GUIWindow, 220, 200, 120, 20);
  openOrClosed3.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  openOrClosed3.setText("Window 3 Open?");
  openOrClosed3.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  openOrClosed3.setOpaque(false);
  openOrClosed3.addEventHandler(this, "openOrClosedBox3");
  openOrClosed3.setSelected(true);
  openOrClosed4 = new GCheckbox(GUIWindow, 220, 250, 120, 20);
  openOrClosed4.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  openOrClosed4.setText("Window 4 Open?");
  openOrClosed4.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  openOrClosed4.setOpaque(false);
  openOrClosed4.addEventHandler(this, "openOrClosedBox4");
  openOrClosed4.setSelected(true);
  dropList1 = new GDropList(GUIWindow, 300, 60, 90, 80, 3, 10);
  dropList1.setItems(loadStrings("list_810305"), 0);
  dropList1.addEventHandler(this, "startHungerControl");
  startHunger = new GLabel(GUIWindow, 212, 49, 80, 40);
  startHunger.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  startHunger.setText("Starting Hunger Level");
  startHunger.setOpaque(false);
  instructions = new GLabel(GUIWindow, 0, 15, 400, 20);
  instructions.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  instructions.setText("You can adjust the following controls to alternate the outcome");
  instructions.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  instructions.setOpaque(false);
  GUIWindow.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow GUIWindow;
GCheckbox openOrClosed1; 
GDropList weather; 
GLabel weather2; 
GCustomSlider maxPeopleInLine; 
GLabel peopleInLine; 
GButton button1; 
GCheckbox openOrClosed2; 
GCheckbox openOrClosed3; 
GCheckbox openOrClosed4; 
GDropList dropList1; 
GLabel startHunger; 
GLabel instructions; 
